package models
import(
	"net/http"
	"net/url"
	"log"
	"io/ioutil"
	"encoding/json"
)

type AutoGenerated struct {
	RefreshToken  string `json:"refresh_token"`
	ExpiresIn     int    `json:"expires_in"`
	Scope         string `json:"scope"`
	SessionKey    string `json:"session_key"`
	AccessToken   string `json:"access_token"`
	SessionSecret string `json:"session_secret"`
}

var AutoGeneratedValue AutoGenerated
const token_url="https://aip.baidubce.com/oauth/2.0/token" 
const api_key="aQTKQRiNE2KUUyFH9KTY8p6G"
const secret_key="vyic6ut3ZERFvK1hnpsoy0R5ppVxQyP7"

const RecognitionUrl="https://aip.baidubce.com/rest/2.0/face/v1/detect"

func init(){
	InitRecognitionServices()
}
//获取百度Token
func InitRecognitionServices()bool{
	res,err:=http.PostForm(token_url,url.Values{"grant_type":{"client_credentials"},"client_id":{api_key},"client_secret":{secret_key}})
	if err != nil {
        log.Println(err.Error())
        return false
	}
	defer res.Body.Close()
	  body,err := ioutil.ReadAll(res.Body)
    if err != nil {
		log.Println(err.Error())
		return false
	}
	err_unmarshal:=json.Unmarshal(body,&AutoGeneratedValue)
	   if err_unmarshal != nil {
		log.Println(err_unmarshal.Error())
		return false
	} 
	log.Println("baidu token get success")
	return true
}